title: 照明胧
description: > # this means to ignore newlines until "baseurl:"
  这是用于记录日常一些笔记的blog，废弃了一年多，要重新启动了。内容有关js,vue,react,ts,node,koa2。如果你进入了这里，希望能对你有帮助
permalink: ":title/"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "mmmml-zhao.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 照明胧 # add your name
author-img: avatar.jpg # add your photo
about-author: 照明胧的个人blog # add description
github: mmmml-zhao # add your Github handle
email: 690902636@qq.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
